# Generated by Django 3.2.9 on 2021-11-30 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_auto_20211130_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='goal_progress',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='habit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habit_tracker.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
