# Generated by Django 3.2.9 on 2021-12-01 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_auto_20211130_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_entered',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
