# Generated by Django 3.2.9 on 2021-12-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_alter_record_date_entered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='habit_id',
        ),
        migrations.AddField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habit_tracker.habit'),
        ),
    ]
